Add Backend Setup
Wits-SD3-404-Effort-not-Found/SPS-Backend pull request #2
Opened 2023-03-27 20:29 UTC by orwellian225

Add logging
Add config
Add rocket (http api crate)

2023-03-28 12:57 UTC, Konstantinos1504 reviewed
We change the MIT license in a future date, definetly

2023-03-28 13:08 UTC, Konstantinos1504 requested changes

2023-03-28 13:08 UTC, Konstantinos1504 commented on src/endpoints/tests.rs
> +fn test_index() {
Change name to Tamlin's convention
```rust
fn test_index_none_ok() {
```

2023-03-28 20:03 UTC, orwellian225 commented on src/endpoints/tests.rs
> +fn test_index() {
will do

2023-03-28 20:20 UTC, Zach-schwark approved these changes

2023-03-28 21:45 UTC, Konstantinos1504 approved these changes
good

2023-03-29 05:33 UTC, Zach-schwark approved these changes

2023-03-29 05:38 UTC, merged